### ISSUE TITLE
Do exposure_time and timestamp matters?

### ISSUE THREAD

**Issue by fandulu** [ethliup/SelfDeblur#2]
Could I ask if exposure_time and timestamp are unknown, is it fine to put an arbitrary number for exposure_time and an ascendant sequence for timestamp? Since I could not find they are used in the paper formulas or in the code.

**Comment by ethliup** [comment]
No, it is required and is very important (including the frame interval). It is used in the code. You can find it at line 130-131 from SelfDeblur/model_self_deblur_net.py . Also, you can find it from equation 1&2 in the supplementary material of the paper https://arxiv.org/abs/2002.04070 .

**Comment by fandulu** [comment]
I see. Thanks again for your answering.
