### ISSUE TITLE
I have only blurred imagesets, Can I train your network using my-datasets?

### ISSUE THREAD

**Issue by edwardcho** [ethliup/SelfDeblur#4]
Hello Sir,

I have interesting image-deblurring.
I have blurred images only. 

Many networks should need blurred images and sharp images as pair.
So I can't train other networks that need blurred images and sharp images.

In our Abstract of paper, I saw that your network needs blurred images only.
But I saw that your network need paired_image_list.log. ("please prepare a paired_image_list.log file")
What is this??
Does your network need paired-images on train??

Thanks,
Edward Cho.

**Comment by edwardcho** [comment]
And, 
I saw blur_image_paths and sharp_image_paths in dataloader.py
If so, your networks should need paired-images (blurred image vs sharp image) ??

![image](https://user-images.githubusercontent.com/29569662/158958657-02a62ced-f8b7-4a09-9df9-aa10c450a2eb.png)

Thanks,
Edward Cho.

**Comment by ethliup** [comment]
Hi Edward,

It does not require the sharp images. You can use the same path as that for blurred images without changing the code. 

peidong

**Comment by edwardcho** [comment]
Hello sir.
Thank you for your response quickly. 
I will try to train using my datasets.

**Comment by edwardcho** [comment]
Hello sir,
I check train.sh of your folder.
If i try to train using my dataset, what should i do change in train.sh ?? 
And, should i do three python codes in train.sh
    (Train deblur net.py
      Train self flow net.py
      Train self deblur net.py)

Thanks,
Edward Cho.
